### PR TITLE
correct blackjack payout

### PR DESCRIPTION
**Pull request by SpudGunMan**
only on the flop is the payout delivered

### CODE REVIEW

**Comment by Himan10** [comment]
That's an idea to make a special "Blackjack" designation but what if a player has more than 2 cards and their sum is equal to 21, then it is still considered as a strong hard. I guess, it would be better if the same condition is split into two, for example: 
```
if value == 21 and len(cards) == 2:
    # better payout either 3.5x or 1.5x
elif value == 21 and len(cards) > 2:
    # not a special condition, just double the money
```

**Comment by SpudGunMan** [comment]
It's strong but.. this is from Wikipedia 

`
A player total of 21 on the first two cards is a "natural" or "blackjack", and the player wins immediately unless the dealer also has one, in which case the hand ties. In the case of a tie ("push" or "standoff"), bets are returned without adjustment. A blackjack beats any hand that is not a blackjack, even one with a value of 21.`

so only the two card black jack payout is increased to 3:1 or (bet)*1.5 all other bets paid at 1:1

**Comment by SpudGunMan** [comment]
Currently code is payout win, however not a push. IMO it's more fun

**Comment by Himan10** [comment]
Okay, we can make it the way as you've mentioned above. If the player hits 21 with more than 2 cards in-hand, they need to wait for dealer's move or else if player's cards total is 21 with only 2 cards in-hand, then it gets recognized and declared as "blackjack" right away.

**Comment by Himan10** [comment]
@SpudGunMan, would you like to take a look at different code? Actually I am looking for contributors who can contribute with their ideas or code snippets if they'd like, the code and idea is currently in its initial stage. Hit me up if you'd like to contribute their as well.

**Pull request merged**
